"""
Business seed data — 30+ rural/semi-urban micro-entrepreneur business opportunities.

ALL FINANCIAL VALUES ARE ESTIMATES FOR ADVISORY PURPOSES ONLY.
Actual results depend on location, execution, market conditions, and individual effort.
These figures should NOT be treated as guaranteed income.

Run this module directly:
    python -m app.seed_businesses

Safe to run multiple times (skips existing records by name).
"""
import asyncio
import sys
from pathlib import Path

# Allow running as a module from backend/
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from sqlalchemy import select
from app.database.db import AsyncSessionLocal, init_db
from app.models.business import Business

# ─────────────────────────────────────────────────────────────────────────────
# Dataset — 32 businesses
# ─────────────────────────────────────────────────────────────────────────────
BUSINESSES: list[dict] = [

    # ── Agriculture & Allied ─────────────────────────────────────────────────
    {
        "name": "Dairy Farming (Small Scale)",
        "category": "Agriculture & Allied",
        "description": "Keep 3–5 milch cows/buffaloes and sell milk directly to consumers or a local cooperative. High demand in both rural and urban areas.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 80000, "max_investment": 200000,
        "estimated_monthly_revenue_min": 25000, "estimated_monthly_revenue_max": 60000,
        "estimated_monthly_expenses_min": 15000, "estimated_monthly_expenses_max": 35000,
        "estimated_monthly_profit_min": 10000, "estimated_monthly_profit_max": 25000,
        "risk_level": "Medium",
        "required_skills": "Animal husbandry, Livestock care, Milk handling",
        "risk_factors": "Animal disease, Feed price fluctuation, Seasonal demand",
        "key_challenges": "Initial animal cost, Veterinary expenses, Milk spoilage",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },
    {
        "name": "Poultry Farming (Broiler)",
        "category": "Agriculture & Allied",
        "description": "Raise broiler chickens for meat. Cycle of 6–7 weeks per batch. Suitable for contract farming to reduce risk.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 50000, "max_investment": 150000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 50000,
        "estimated_monthly_expenses_min": 14000, "estimated_monthly_expenses_max": 35000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 15000,
        "risk_level": "Medium",
        "required_skills": "Poultry care, Feed management, Biosecurity",
        "risk_factors": "Bird flu risk, Feed price volatility, Market price fluctuation",
        "key_challenges": "Disease management, Feed sourcing, Market linkage",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 6,
    },
    {
        "name": "Goat Farming",
        "category": "Agriculture & Allied",
        "description": "Rear goats for meat and milk. Lower capital than cattle. High demand during festivals. Well-suited for small land holdings.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 40000, "max_investment": 120000,
        "estimated_monthly_revenue_min": 10000, "estimated_monthly_revenue_max": 30000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 5000, "estimated_monthly_profit_max": 15000,
        "risk_level": "Low",
        "required_skills": "Animal care, Grazing management, Basic health care",
        "risk_factors": "Disease, Predator loss, Seasonal demand",
        "key_challenges": "Grazing land, Veterinary access, Festival-dependent income",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Mushroom Cultivation",
        "category": "Agriculture & Allied",
        "description": "Grow oyster or button mushrooms indoors with low capital. High value crop with 45-day cycles. Growing urban demand.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 60000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 35000,
        "estimated_monthly_expenses_min": 7000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 8000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Medium",
        "required_skills": "Mushroom cultivation, Hygiene, Substrate preparation",
        "risk_factors": "Contamination risk, Temperature control, Market access",
        "key_challenges": "Technical training required, Humidity control, Storage",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Organic Vegetable Farming",
        "category": "Agriculture & Allied",
        "description": "Grow chemical-free vegetables for direct sale to consumers, organic stores, or restaurants. Premium pricing possible.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 15000, "max_investment": 50000,
        "estimated_monthly_revenue_min": 10000, "estimated_monthly_revenue_max": 30000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 12000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 18000,
        "risk_level": "Low",
        "required_skills": "Farming, Organic practices, Market linkage",
        "risk_factors": "Weather dependency, Pest management, Market price",
        "key_challenges": "Organic certification, Distribution network",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 12,
    },
    {
        "name": "Plant Nursery",
        "category": "Agriculture & Allied",
        "description": "Grow and sell saplings, flowering plants, and kitchen garden plants. Urban gardening boom drives demand.",
        "business_type": "Agriculture",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 70000,
        "estimated_monthly_revenue_min": 12000, "estimated_monthly_revenue_max": 35000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 7000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Low",
        "required_skills": "Horticulture, Plant care, Propagation",
        "risk_factors": "Seasonal demand, Pest/disease, Water availability",
        "key_challenges": "Space requirement, Slow initial returns",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },
    {
        "name": "Animal Feed Business",
        "category": "Agriculture & Allied",
        "description": "Supply compound feed, hay, and supplements to local dairy and poultry farmers. Steady B2B demand.",
        "business_type": "Distribution",
        "suitable_for_rural": True,
        "min_investment": 50000, "max_investment": 150000,
        "estimated_monthly_revenue_min": 40000, "estimated_monthly_revenue_max": 80000,
        "estimated_monthly_expenses_min": 30000, "estimated_monthly_expenses_max": 60000,
        "estimated_monthly_profit_min": 10000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Low",
        "required_skills": "Supply chain, Animal nutrition basics, Customer relations",
        "risk_factors": "Price volatility, Storage, Competition",
        "key_challenges": "Working capital management, Transport",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 6,
    },

    # ── Retail & Distribution ─────────────────────────────────────────────────
    {
        "name": "Kirana / Grocery Store",
        "category": "Retail & Distribution",
        "description": "Neighbourhood grocery store selling daily essentials. Predictable demand, repeat customers. Works in any village or town.",
        "business_type": "Retail",
        "suitable_for_rural": True,
        "min_investment": 80000, "max_investment": 250000,
        "estimated_monthly_revenue_min": 80000, "estimated_monthly_revenue_max": 200000,
        "estimated_monthly_expenses_min": 65000, "estimated_monthly_expenses_max": 170000,
        "estimated_monthly_profit_min": 15000, "estimated_monthly_profit_max": 30000,
        "risk_level": "Low",
        "required_skills": "Retail operations, Inventory management, Customer service",
        "risk_factors": "Competition from chains, Credit customers, Theft",
        "key_challenges": "Working capital, SKU management, Location",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Vegetable & Fruit Distribution",
        "category": "Retail & Distribution",
        "description": "Buy from farmers / wholesale market and distribute to retail shops or sell directly via cart/stall.",
        "business_type": "Distribution",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 60000,
        "estimated_monthly_revenue_min": 30000, "estimated_monthly_revenue_max": 80000,
        "estimated_monthly_expenses_min": 22000, "estimated_monthly_expenses_max": 60000,
        "estimated_monthly_profit_min": 8000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Medium",
        "required_skills": "Negotiation, Logistics, Perishable handling",
        "risk_factors": "Spoilage, Price volatility, Weather",
        "key_challenges": "Daily early morning work, Perishable losses",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 2,
    },
    {
        "name": "Milk Distribution",
        "category": "Retail & Distribution",
        "description": "Collect milk from farmers and deliver to households and shops. Very early morning schedule. Good margins possible.",
        "business_type": "Distribution",
        "suitable_for_rural": True,
        "min_investment": 15000, "max_investment": 50000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 50000,
        "estimated_monthly_expenses_min": 14000, "estimated_monthly_expenses_max": 35000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 15000,
        "risk_level": "Low",
        "required_skills": "Route management, Milk quality, Customer service",
        "risk_factors": "Spoilage, Seasonal supply, Vehicle breakdown",
        "key_challenges": "Early mornings, Scaling collection network",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 3,
    },
    {
        "name": "Mobile Accessories Shop",
        "category": "Retail & Distribution",
        "description": "Sell smartphone accessories, covers, earphones, chargers. Low investment, high footfall in any market area.",
        "business_type": "Retail",
        "suitable_for_rural": True,
        "min_investment": 30000, "max_investment": 80000,
        "estimated_monthly_revenue_min": 25000, "estimated_monthly_revenue_max": 60000,
        "estimated_monthly_expenses_min": 16000, "estimated_monthly_expenses_max": 40000,
        "estimated_monthly_profit_min": 9000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Low",
        "required_skills": "Retail, Basic smartphone knowledge, Customer service",
        "risk_factors": "Online competition, Fashion changes, Obsolescence",
        "key_challenges": "Online price competition, Stock management",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 2,
    },
    {
        "name": "Agricultural Inputs Supply",
        "category": "Retail & Distribution",
        "description": "Retail shop for seeds, fertilizers, pesticides, and tools. Essential service for farming communities.",
        "business_type": "Retail",
        "suitable_for_rural": True,
        "min_investment": 60000, "max_investment": 180000,
        "estimated_monthly_revenue_min": 60000, "estimated_monthly_revenue_max": 150000,
        "estimated_monthly_expenses_min": 48000, "estimated_monthly_expenses_max": 120000,
        "estimated_monthly_profit_min": 12000, "estimated_monthly_profit_max": 30000,
        "risk_level": "Low",
        "required_skills": "Agricultural knowledge, Retail, Licensing",
        "risk_factors": "Seasonal demand, Licensing requirements, Competition",
        "key_challenges": "Regulatory compliance, Seasonal cash flow",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },

    # ── Services ──────────────────────────────────────────────────────────────
    {
        "name": "Tailoring & Boutique",
        "category": "Services",
        "description": "Custom stitching, alteration, and garment design. Home-based possible. Festival season demand is very high.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 15000, "max_investment": 60000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 40000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 12000,
        "estimated_monthly_profit_min": 11000, "estimated_monthly_profit_max": 28000,
        "risk_level": "Low",
        "required_skills": "Tailoring, Sewing, Garment design, Cutting",
        "risk_factors": "Seasonal demand, Competition, Fashion trends",
        "key_challenges": "Building clientele, Festival workload spikes",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 3,
    },
    {
        "name": "Mobile Phone Repair",
        "category": "Services",
        "description": "Repair smartphones, feature phones, and accessories. Recurring demand. Can be combined with accessories retail.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 60000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 40000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 12000,
        "estimated_monthly_profit_min": 11000, "estimated_monthly_profit_max": 28000,
        "risk_level": "Low",
        "required_skills": "Mobile repair, Electronics, Soldering, Diagnostics",
        "risk_factors": "New phone models, Online competition, Spare parts cost",
        "key_challenges": "Keeping up with new models, Spare part sourcing",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Two-Wheeler Repair Workshop",
        "category": "Services",
        "description": "Service and repair motorcycles and scooters. Essential in rural India where two-wheelers are primary transport.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 40000, "max_investment": 120000,
        "estimated_monthly_revenue_min": 25000, "estimated_monthly_revenue_max": 60000,
        "estimated_monthly_expenses_min": 10000, "estimated_monthly_expenses_max": 25000,
        "estimated_monthly_profit_min": 15000, "estimated_monthly_profit_max": 35000,
        "risk_level": "Low",
        "required_skills": "Mechanical skills, Two-wheeler repair, Electrical",
        "risk_factors": "Competition from brand workshops, Parts availability",
        "key_challenges": "Skilled mechanic hiring, Tool investment",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 6,
    },
    {
        "name": "Computer & Laptop Repair",
        "category": "Services",
        "description": "Provide computer repair, data recovery, and software services. Growing demand with digitisation.",
        "business_type": "Service",
        "suitable_for_rural": False,
        "min_investment": 25000, "max_investment": 70000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 40000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 10000,
        "estimated_monthly_profit_min": 11000, "estimated_monthly_profit_max": 30000,
        "risk_level": "Low",
        "required_skills": "Computer hardware, Software, Networking, Troubleshooting",
        "risk_factors": "Online tech support competition, Rapid tech changes",
        "key_challenges": "Staying current with technology, Sourcing parts",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 3,
    },
    {
        "name": "Digital Service Center / CSC",
        "category": "Services",
        "description": "Common Service Center offering Aadhaar, PAN, ration card, banking, utility bill payments. Government-backed scheme available.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 30000, "max_investment": 80000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 40000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 12000,
        "estimated_monthly_profit_min": 10000, "estimated_monthly_profit_max": 28000,
        "risk_level": "Low",
        "required_skills": "Computer, Internet, Customer service, Government portals",
        "risk_factors": "Internet downtime, Low per-transaction margin",
        "key_challenges": "Registration process, Internet reliability",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 8,
    },
    {
        "name": "Photography & Videography",
        "category": "Services",
        "description": "Wedding, event, and portrait photography. High demand for festivals, weddings, and school events.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 50000, "max_investment": 150000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 50000,
        "estimated_monthly_expenses_min": 3000, "estimated_monthly_expenses_max": 12000,
        "estimated_monthly_profit_min": 12000, "estimated_monthly_profit_max": 38000,
        "risk_level": "Medium",
        "required_skills": "Photography, Editing, Creativity, Client management",
        "risk_factors": "Seasonal demand, Equipment cost, Competition",
        "key_challenges": "Building portfolio, Expensive equipment, Seasonal income",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 6,
    },
    {
        "name": "Printing & Photocopying Center",
        "category": "Services",
        "description": "Print, photocopy, lamination, and stationery services near schools, offices, or government offices.",
        "business_type": "Service",
        "suitable_for_rural": False,
        "min_investment": 40000, "max_investment": 100000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 45000,
        "estimated_monthly_expenses_min": 8000, "estimated_monthly_expenses_max": 18000,
        "estimated_monthly_profit_min": 12000, "estimated_monthly_profit_max": 27000,
        "risk_level": "Low",
        "required_skills": "Computer, Printing, Basic design, Customer service",
        "risk_factors": "Equipment maintenance, Digital shift reducing print demand",
        "key_challenges": "Location dependency, Equipment repair costs",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Beauty Parlour / Salon",
        "category": "Services",
        "description": "Hair cutting, styling, and basic beauty treatments. Home-based or small shop. Women entrepreneurs especially well-suited.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 80000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 45000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 10000, "estimated_monthly_profit_max": 30000,
        "risk_level": "Low",
        "required_skills": "Hair styling, Beauty treatments, Customer service",
        "risk_factors": "Product cost, Seasonal demand, Competition",
        "key_challenges": "Certification/training, Building repeat clientele",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },

    # ── Food & Beverage ───────────────────────────────────────────────────────
    {
        "name": "Tea / Snack Stall",
        "category": "Food & Beverage",
        "description": "Serve tea, coffee, and snacks near bus stands, markets, or offices. Very low capital, instant daily cash flow.",
        "business_type": "Food Service",
        "suitable_for_rural": True,
        "min_investment": 8000, "max_investment": 30000,
        "estimated_monthly_revenue_min": 15000, "estimated_monthly_revenue_max": 35000,
        "estimated_monthly_expenses_min": 8000, "estimated_monthly_expenses_max": 18000,
        "estimated_monthly_profit_min": 7000, "estimated_monthly_profit_max": 17000,
        "risk_level": "Low",
        "required_skills": "Cooking, Customer service, Food hygiene",
        "risk_factors": "Weather, Competition, Location dependency",
        "key_challenges": "Consistency, Food safety compliance",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 2,
    },
    {
        "name": "Small Restaurant / Dhaba",
        "category": "Food & Beverage",
        "description": "Serve meals to daily workers, truckers, or locals. Fixed lunch/dinner schedule. Can earn well near highway or industrial area.",
        "business_type": "Food Service",
        "suitable_for_rural": True,
        "min_investment": 50000, "max_investment": 150000,
        "estimated_monthly_revenue_min": 40000, "estimated_monthly_revenue_max": 100000,
        "estimated_monthly_expenses_min": 28000, "estimated_monthly_expenses_max": 70000,
        "estimated_monthly_profit_min": 12000, "estimated_monthly_profit_max": 30000,
        "risk_level": "Medium",
        "required_skills": "Cooking, Kitchen management, Food safety, Staff management",
        "risk_factors": "Food waste, Staff, Location, Health inspections",
        "key_challenges": "Consistent quality, Working long hours",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 8,
    },
    {
        "name": "Home Bakery",
        "category": "Food & Beverage",
        "description": "Bake cakes, biscuits, and bread from home for events, local shops, and direct orders. Low overhead.",
        "business_type": "Food Production",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 60000,
        "estimated_monthly_revenue_min": 12000, "estimated_monthly_revenue_max": 40000,
        "estimated_monthly_expenses_min": 6000, "estimated_monthly_expenses_max": 20000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Low",
        "required_skills": "Baking, Recipe development, Packaging, Marketing",
        "risk_factors": "Perishable goods, Competition, Seasonal demand",
        "key_challenges": "FSSAI registration, Packaging, Consistent quality",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Catering Service",
        "category": "Food & Beverage",
        "description": "Provide food for weddings, corporate events, and parties. High value per event. Seasonal but lucrative.",
        "business_type": "Food Service",
        "suitable_for_rural": True,
        "min_investment": 30000, "max_investment": 100000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 80000,
        "estimated_monthly_expenses_min": 12000, "estimated_monthly_expenses_max": 55000,
        "estimated_monthly_profit_min": 8000, "estimated_monthly_profit_max": 25000,
        "risk_level": "Medium",
        "required_skills": "Cooking, Event management, Team coordination, Food safety",
        "risk_factors": "Seasonal demand, Last-minute cancellations, Staff reliability",
        "key_challenges": "Managing large volumes, Equipment transport",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 6,
    },
    {
        "name": "Homemade Food Products",
        "category": "Food & Beverage",
        "description": "Produce and sell pickles, chutneys, papads, or snacks. Sell through local shops, markets, or online.",
        "business_type": "Food Production",
        "suitable_for_rural": True,
        "min_investment": 10000, "max_investment": 40000,
        "estimated_monthly_revenue_min": 8000, "estimated_monthly_revenue_max": 30000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 4000, "estimated_monthly_profit_max": 15000,
        "risk_level": "Low",
        "required_skills": "Food preparation, Quality control, Packaging, Marketing",
        "risk_factors": "Shelf life, Regulatory compliance, Competition",
        "key_challenges": "FSSAI license, Consistent supply, Distribution network",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 6,
    },

    # ── Manufacturing / Small Production ─────────────────────────────────────
    {
        "name": "Candle Making",
        "category": "Manufacturing",
        "description": "Produce decorative and regular candles. Sell to temples, events, and retail shops. Home-based possible.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 10000, "max_investment": 40000,
        "estimated_monthly_revenue_min": 10000, "estimated_monthly_revenue_max": 30000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 15000,
        "estimated_monthly_profit_min": 5000, "estimated_monthly_profit_max": 15000,
        "risk_level": "Low",
        "required_skills": "Candle making, Mold work, Packaging, Marketing",
        "risk_factors": "Seasonal demand, Raw material cost, Competition",
        "key_challenges": "Scaling production, Festival-dependent demand",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 3,
    },
    {
        "name": "Soap & Detergent Manufacturing",
        "category": "Manufacturing",
        "description": "Produce bar soap, liquid soap, and detergent for local market. Essential product, steady demand.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 20000, "max_investment": 70000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 50000,
        "estimated_monthly_expenses_min": 12000, "estimated_monthly_expenses_max": 30000,
        "estimated_monthly_profit_min": 8000, "estimated_monthly_profit_max": 20000,
        "risk_level": "Medium",
        "required_skills": "Chemical handling, Manufacturing, Quality control, Packaging",
        "risk_factors": "Chemical safety, Quality control, Raw material prices",
        "key_challenges": "BIS certification, Competition from branded products",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 6,
    },
    {
        "name": "Paper Bag Manufacturing",
        "category": "Manufacturing",
        "description": "Produce eco-friendly paper bags for shops and markets. Demand surging post single-use plastic ban.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 25000, "max_investment": 80000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 55000,
        "estimated_monthly_expenses_min": 12000, "estimated_monthly_expenses_max": 32000,
        "estimated_monthly_profit_min": 8000, "estimated_monthly_profit_max": 23000,
        "risk_level": "Low",
        "required_skills": "Machine operation, Quality control, B2B sales",
        "risk_factors": "Raw paper price, Machine downtime, Competition",
        "key_challenges": "B2B client acquisition, Machine maintenance",
        "setup_time_weeks_min": 3, "setup_time_weeks_max": 6,
    },
    {
        "name": "Spice Grinding & Packaging",
        "category": "Manufacturing",
        "description": "Grind and package common spices (chilli, turmeric, coriander) for retail. Local brand can command premium.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 30000, "max_investment": 100000,
        "estimated_monthly_revenue_min": 25000, "estimated_monthly_revenue_max": 70000,
        "estimated_monthly_expenses_min": 16000, "estimated_monthly_expenses_max": 48000,
        "estimated_monthly_profit_min": 9000, "estimated_monthly_profit_max": 22000,
        "risk_level": "Low",
        "required_skills": "Spice processing, Quality grading, Packaging, FSSAI compliance",
        "risk_factors": "Seasonal raw material price, Adulteration risk, Competition",
        "key_challenges": "FSSAI registration, Consistent quality, Brand building",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },
    {
        "name": "Pickle & Papad Manufacturing",
        "category": "Manufacturing",
        "description": "Produce traditional pickles and papads for local market and online sale. Cottage industry with Govt. support.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 15000, "max_investment": 50000,
        "estimated_monthly_revenue_min": 12000, "estimated_monthly_revenue_max": 35000,
        "estimated_monthly_expenses_min": 6000, "estimated_monthly_expenses_max": 18000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 17000,
        "risk_level": "Low",
        "required_skills": "Food processing, Recipe expertise, Packaging, Quality control",
        "risk_factors": "Shelf life management, Seasonal raw material, Competition",
        "key_challenges": "FSSAI license, Consistent taste, Distribution",
        "setup_time_weeks_min": 2, "setup_time_weeks_max": 4,
    },
    {
        "name": "Agarbatti / Incense Stick Making",
        "category": "Manufacturing",
        "description": "Produce incense sticks for temples and households. High demand, especially for export. Home-based possible.",
        "business_type": "Manufacturing",
        "suitable_for_rural": True,
        "min_investment": 10000, "max_investment": 35000,
        "estimated_monthly_revenue_min": 8000, "estimated_monthly_revenue_max": 25000,
        "estimated_monthly_expenses_min": 4000, "estimated_monthly_expenses_max": 14000,
        "estimated_monthly_profit_min": 4000, "estimated_monthly_profit_max": 11000,
        "risk_level": "Low",
        "required_skills": "Incense making, Raw material sourcing, Quality",
        "risk_factors": "Raw material quality, Competition, Health hazard if not ventilated",
        "key_challenges": "Mass production for viability, Market linkage",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 3,
    },

    # ── Additional High-Impact Businesses ────────────────────────────────────
    {
        "name": "Fertilizer & Pesticide Retail",
        "category": "Retail & Distribution",
        "description": "Licensed retail shop for agricultural chemicals. Essential rural service with recurring seasonal demand.",
        "business_type": "Retail",
        "suitable_for_rural": True,
        "min_investment": 80000, "max_investment": 200000,
        "estimated_monthly_revenue_min": 80000, "estimated_monthly_revenue_max": 200000,
        "estimated_monthly_expenses_min": 65000, "estimated_monthly_expenses_max": 165000,
        "estimated_monthly_profit_min": 15000, "estimated_monthly_profit_max": 35000,
        "risk_level": "Medium",
        "required_skills": "Agricultural knowledge, Licensing, Retail, Safety handling",
        "risk_factors": "Regulatory risk, Seasonal cash flow, Chemical safety",
        "key_challenges": "License requirement, Seasonal working capital",
        "setup_time_weeks_min": 6, "setup_time_weeks_max": 12,
    },
    {
        "name": "Tuition / Coaching Center",
        "category": "Services",
        "description": "Provide private tuition for school children. Can be started from home. Growing demand in rural areas.",
        "business_type": "Service",
        "suitable_for_rural": True,
        "min_investment": 5000, "max_investment": 30000,
        "estimated_monthly_revenue_min": 8000, "estimated_monthly_revenue_max": 30000,
        "estimated_monthly_expenses_min": 2000, "estimated_monthly_expenses_max": 8000,
        "estimated_monthly_profit_min": 6000, "estimated_monthly_profit_max": 22000,
        "risk_level": "Low",
        "required_skills": "Teaching, Subject expertise, Communication, Patience",
        "risk_factors": "Competition, Seasonal demand (school year), Online classes",
        "key_challenges": "Building student base, Quality consistency",
        "setup_time_weeks_min": 1, "setup_time_weeks_max": 2,
    },
    {
        "name": "Fruit Processing (Juice / Pulp)",
        "category": "Manufacturing",
        "description": "Process local fruits into juice, pulp, or dried snacks. Supports local farmers and reduces post-harvest loss.",
        "business_type": "Food Production",
        "suitable_for_rural": True,
        "min_investment": 40000, "max_investment": 120000,
        "estimated_monthly_revenue_min": 25000, "estimated_monthly_revenue_max": 70000,
        "estimated_monthly_expenses_min": 16000, "estimated_monthly_expenses_max": 45000,
        "estimated_monthly_profit_min": 9000, "estimated_monthly_profit_max": 25000,
        "risk_level": "Medium",
        "required_skills": "Food processing, Machine operation, Hygiene, FSSAI compliance",
        "risk_factors": "Seasonal fruit supply, Perishable nature, Equipment cost",
        "key_challenges": "Consistent raw material, Cold storage, Certification",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },
    {
        "name": "Tent & Event Rentals",
        "category": "Services",
        "description": "Rent tents, chairs, sound systems for weddings and events. High income per event with good community network.",
        "business_type": "Rental",
        "suitable_for_rural": True,
        "min_investment": 80000, "max_investment": 200000,
        "estimated_monthly_revenue_min": 20000, "estimated_monthly_revenue_max": 70000,
        "estimated_monthly_expenses_min": 5000, "estimated_monthly_expenses_max": 20000,
        "estimated_monthly_profit_min": 15000, "estimated_monthly_profit_max": 50000,
        "risk_level": "Medium",
        "required_skills": "Event management, Logistics, Customer relations, Maintenance",
        "risk_factors": "Seasonal wedding season, Weather damage, Storage space",
        "key_challenges": "High upfront investment, Storage and maintenance",
        "setup_time_weeks_min": 4, "setup_time_weeks_max": 8,
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# Seeder
# ─────────────────────────────────────────────────────────────────────────────

async def seed_businesses() -> tuple[int, int]:
    """
    Insert businesses that don't already exist (matched by name).
    Returns (inserted_count, skipped_count).

    Startup already initializes tables; do not recurse into init_db(), or the
    app can spin into a circular seeding loop during warm starts.
    """
    inserted = 0
    skipped = 0

    async with AsyncSessionLocal() as session:
        for data in BUSINESSES:
            result = await session.execute(
                select(Business).where(Business.name == data["name"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                skipped += 1
                continue

            biz = Business(**data)
            session.add(biz)
            inserted += 1

        await session.commit()

    return inserted, skipped


if __name__ == "__main__":
    async def main():
        print("Seeding business database...")
        inserted, skipped = await seed_businesses()
        print(f"Done: {inserted} inserted, {skipped} skipped (already existed)")
        print(f"   Total businesses in dataset: {len(BUSINESSES)}")
        print()
        print("NOTE: All financial values are ESTIMATES for advisory purposes only.")

    asyncio.run(main())
